version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "sample-app"
    volumes:
      - ./frontend:/frontend/
      - ./backend:/backend/
    ports:
      - "80:80"
    tty: true

